# Generated by Django 2.0 on 2019-07-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_jongmok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jongmok',
        ),
    ]
